### ISSUE TITLE
Island shapes

### ISSUE THREAD

**Issue by redblobgames** [staff0rd/polygon-map-unity#2]
To get island shapes like the original mapgen2, you can tweak the IslandShape `makePerlin` noise function:

1. Rescale q from the 0…50 range to the -1…+1 range by using `q = new Vector2(q.x/25-1, q.y/25-1)`
2. Set `result = perlin > checkValue` instead of `perlin > .3`

The 0.3 values might have to be tweaked to change the roundness and size of the island. (The 0.3 values are tuned Flash's perlin noise and not necessarily the best values for Unity's)

**Comment by staff0rd** [comment]
Thanks @redblobgames, update worked as expected.  Love the articles!
